### ISSUE TITLE
导入报错了哦

### ISSUE THREAD

**Issue by weitemi** [xkli/WXSample#1]
Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
Error:Execution failed for task ':app:weex'.
> execCommand == null!

**Comment by jintaixizhao** [comment]
同样遇到这个问题了，求解！

**Comment by xkli** [comment]
Now the project is working properly
