### ISSUE TITLE
lost hello.js

### ISSUE THREAD

**Issue by LeeYewKuan** [xkli/WXSample#2]
In the demo, lost the file  <build/hello.js>,Error info:

> System.err: java.io.FileNotFoundException: build/hello.js

please commit the file.

so, I create a empty file hello.js in the build. run this demo, still error,error info:

> com.weex.sample E/weex: launchInspector HackAssertionException com.taobao.weex.utils.WXHack$HackDeclaration$HackAssertionException: java.lang.ClassNotFoundException: com.taobao.weex.devtools.debug.DebugServerProxy

**Comment by xkli** [comment]
@LeeYewKuan Now the project is working properly。
